# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1d41eb7d09fa255d30f66a0a1ca7cadada8294dc93a6f53040329523604e277327609a53639f0384284d1c722004a816c0015a387626e84fa1b6307f8b880d1

test:
  secret_key_base: 65ef8988ea1b85a5861adc5b5065097ab99ef2db97b8332c3ce59fb9ee4b6e6a9a0260c252d89cf014b17897b676eee6ab02e7d9c7468035a1b39847f8c7bd8d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
